from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from pathlib import Path


def test_tt_emule_environment_check_unavailable_is_clear() -> None:
    env = _without_tt_emule_env()
    completed = subprocess.run(
        [
            sys.executable,
            "experimental/tt_emule_qmul/check_environment.py",
        ],
        check=False,
        capture_output=True,
        text=True,
        env=env,
    )

    assert completed.returncode == 2
    assert "tt-emule environment unavailable" in completed.stderr
    assert "Traceback" not in completed.stderr


def test_tt_emule_environment_check_accepts_fake_roots(
    tmp_path: Path,
) -> None:
    tt_metal = tmp_path / "tt-metal"
    tt_emule = tmp_path / "tt-emule"
    (tt_metal / "tt_metal").mkdir(parents=True)
    (tt_metal / "CMakeLists.txt").write_text("cmake_minimum_required(VERSION 3.24)\n")
    (tt_emule / "include" / "tt_emule").mkdir(parents=True)
    (tt_emule / "CMakeLists.txt").write_text("cmake_minimum_required(VERSION 3.24)\n")

    completed = subprocess.run(
        [
            sys.executable,
            "experimental/tt_emule_qmul/check_environment.py",
            "--skip-platform-check",
            "--tt-metal-root",
            str(tt_metal),
            "--tt-emule-root",
            str(tt_emule),
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    assert "tt-metal root detected" in completed.stdout
    assert "tt-emule root detected" in completed.stdout
    assert "does not run a kernel" in completed.stdout


def test_tt_emule_build_prereq_accepts_lowercase_metalium_config(tmp_path: Path) -> None:
    module = _load_script("experimental/tt_emule_qmul/check_build_prereqs.py")
    tt_metal = tmp_path / "tt-metal"
    build_emule = tt_metal / "build_emule"
    build_emule.mkdir(parents=True)
    (build_emule / "tt-metalium-config.cmake").write_text("# generated by tt-metal\n")
    (build_emule / "Metalium.cmake").write_text("# exported targets\n")

    assert module._find_metalium_package(tt_metal) == build_emule


def test_tt_emule_build_prereq_rejects_incomplete_metalium_config(tmp_path: Path) -> None:
    module = _load_script("experimental/tt_emule_qmul/check_build_prereqs.py")
    tt_metal = tmp_path / "tt-metal"
    build_emule = tt_metal / "build_emule"
    build_emule.mkdir(parents=True)
    (build_emule / "tt-metalium-config.cmake").write_text("# generated by tt-metal\n")

    assert module._find_metalium_package(tt_metal) is None


def _without_tt_emule_env() -> dict[str, str]:
    env = os.environ.copy()
    env.pop("TT_METAL_HOME", None)
    env.pop("TT_METALIUM_HOME", None)
    env.pop("TT_EMULE_HOME", None)
    return env


def _load_script(path: str):
    script_path = Path(path)
    spec = importlib.util.spec_from_file_location(script_path.stem, script_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules.pop("check_environment", None)
    sys.path.insert(0, str(script_path.parent))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop("check_environment", None)
        sys.path.pop(0)
    return module
